### ISSUE TITLE
TypeError on Python 3

### ISSUE THREAD

**Issue by jaraco** [btubbs/sseclient#13]
When deploying Velociraptor's web proc on Python 3, we see this error in the logs:

```
Traceback (most recent call last):
  File "/app/.heroku/venv/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/app/.heroku/venv/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/app/.heroku/venv/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 114, in handle_request
    for item in respiter:
  File "/app/.heroku/venv/lib/python3.6/site-packages/newrelic/api/web_transaction.py", line 646, in __iter__
    for item in self.generator:
  File "/app/.heroku/venv/lib/python3.6/site-packages/newrelic/api/web_transaction.py", line 1053, in __iter__
    for data in self.iterable:
  File "/app/.heroku/venv/lib/python3.6/site-packages/vr/server/events.py", line 51, in __iter__
    yield self.next()
  File "/app/.heroku/venv/lib/python3.6/site-packages/vr/server/events.py", line 61, in next
    return ev.dump()
  File "/app/.heroku/venv/lib/python3.6/site-packages/sseclient.py", line 116, in dump
    lines.extend('data: %s' % d for d in self.data.split('\n'))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by jaraco** [comment]
I see that sseclient seems to be handling unicode properly since 0.0.8 or so, so probably what needs to happen is VR needs to ensure the data is unicode and not bytes.
